[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：不支持
;增强国外GFW：不支持


ruleset=🐸手动选择,https://raw.githubusercontent.com/mato2021/ACL4SSR/main/Clash/Twitter.list
ruleset=🐸手动选择,https://raw.githubusercontent.com/mato2021/ACL4SSR/main/Clash/Telegram.list
ruleset=🐸手动选择,https://raw.githubusercontent.com/mato2021/ACL4SSR/main/Clash/YouTube.list
ruleset=🐸手动选择,https://raw.githubusercontent.com/mato2021/ACL4SSR/main/Clash/GitHub.list
ruleset=🐸手动选择,https://raw.githubusercontent.com/mato2021/ACL4SSR/refs/heads/main/Clash/Whatsapp.list

ruleset=🛑全球拦截,https://raw.githubusercontent.com/mato2021/ACL4SSR/main/Clash/Ad.list
ruleset=🐸手动选择,https://raw.githubusercontent.com/mato2021/ACL4SSR/main/Clash/Microsoft.list


;ruleset=🎯 全球直连,[]GEOIP,LAN🐟
ruleset=🍃中国大陆,[]GEOIP,CN
ruleset=🐸手动选择,[]FINAL

custom_proxy_group=🐸手动选择`select`[]♻️自动选择`(BWG|CF|US|JP|SG|TW|移动|电信|日本|美国|坡县|弯弯)
custom_proxy_group=♻️自动选择`url-test`(BWG|CF|US|JP|SG|TW|移动|电信|日本|美国|坡县|弯弯)`http://www.gstatic.com/generate_204`120
;custom_proxy_group=🇭🇰 香港节点`url-test`(HK)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🇯🇵 日本节点`url-test`(JP|RB)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🇹🇼 台湾节点`url-test`(TW)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🇸🇬 新加坡节点`url-test`(SG)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🇺🇸 美国节点`url-test`(US)`http://www.gstatic.com/generate_204`300
;custom_proxy_group=🇵🇭 菲律宾节点`select`(PH)
;custom_proxy_group=🔥 优选域名`select`(YM)
custom_proxy_group=🍃中国大陆`select`[]DIRECT
custom_proxy_group=🛑全球拦截`select`[]REJECT
;custom_proxy_group=🐟 漏网之鱼`select`(.*)

enable_rule_generator=true
overwrite_original_rules=true

